spring:
  application:
    name: tianmu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.53.45.251:13306/tianmu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: gK3T9n%q2M@j7Z9

  elasticsearch:
    uris: http://120.53.45.251:9200  # 你的ES地址
    username: elastic      # 如果有认证
    password: tianmu
    connection-timeout: 5s
    socket-timeout: 30s


  data:
    redis:
      database: 15
      host: 120.53.45.251
      port: 6379
      timeout: 50000
      password: "e65K4t8w2"
      # Redis 服务器密码（当前未启用）
      # 配置 redis 连接池
      lettuce:
        pool:
          # 链接池中最小的空闲链接 默认为 0
          min-idle: 4
          # 链接池中最大的空闲连接 默认为 8
          max-idle: 8
          #连接池中最大数据库链接数 默认为 8
          max-active: 8
          #连接池最大阻塞等待时间
          max-wait: 5000ms

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

minio:
  url: http://120.53.45.251:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: tianmu-upload


netty:
  port: 9101



rocketmq:
  name-server: 120.53.45.251:9876
  producer:
    group: tianmuorange-producer-group
  consumer:
    group: tianmuorange-consumer-group
server:
  port: 8101                          # Spring Boot 服务监听端口
  servlet:
    context-path: /api

canal:
  server:
    host: 120.53.45.251
    port: 11111
  destination: example
  username: canal
  password: canal
  filter: ".*\\..*"
  client:
    heartbeat:
      interval: 2000    # 心跳间隔(毫秒)
      timeout: 3000    # 心跳超时(毫秒)
    socket:
      timeout: 6000    # socket超时(毫秒)